# generated by datamodel-codegen:
#   filename:  resources/openapi_spec.json
#   timestamp: 2025-11-18T14:02:41+00:00

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, Field


class PlaneInstance(BaseModel):
    callsign: str = Field(..., title="Callsign")
    lat: float = Field(..., title="Lat")
    lng: float = Field(..., title="Lng")


class PlaneList(BaseModel):
    planes: Optional[list[PlaneInstance]] = Field(None, title="Planes")


class V2ResponseLastPosition(BaseModel):
    lat: float = Field(..., title="Lat")
    lon: float = Field(..., title="Lon")
    nic: int = Field(..., title="Nic")
    rc: int = Field(..., title="Rc")
    seen_pos: float = Field(..., title="Seen Pos")


class ValidationError(BaseModel):
    loc: list[Union[str, int]] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class HTTPValidationError(BaseModel):
    detail: Optional[list[ValidationError]] = Field(None, title="Detail")


class V2ResponseAcItem(BaseModel):
    alert: Optional[int] = Field(None, title="Alert")
    alt_baro: Optional[Union[int, str]] = Field(None, title="Alt Baro")
    alt_geom: Optional[int] = Field(None, title="Alt Geom")
    baro_rate: Optional[int] = Field(None, title="Baro Rate")
    category: Optional[str] = Field(None, title="Category")
    emergency: Optional[str] = Field(None, title="Emergency")
    flight: Optional[str] = Field(None, title="Flight")
    gs: Optional[float] = Field(None, title="Gs")
    gva: Optional[int] = Field(None, title="Gva")
    hex: str = Field(..., title="Hex")
    lat: Optional[float] = Field(None, title="Lat")
    lon: Optional[float] = Field(None, title="Lon")
    messages: int = Field(..., title="Messages")
    mlat: list[str] = Field(..., title="Mlat")
    nac_p: Optional[int] = Field(None, title="Nac P")
    nac_v: Optional[int] = Field(None, title="Nac V")
    nav_altitude_mcp: Optional[int] = Field(None, title="Nav Altitude Mcp")
    nav_heading: Optional[float] = Field(None, title="Nav Heading")
    nav_qnh: Optional[float] = Field(None, title="Nav Qnh")
    nic: Optional[int] = Field(None, title="Nic")
    nic_baro: Optional[int] = Field(None, title="Nic Baro")
    r: Optional[str] = Field(None, title="R")
    rc: Optional[int] = Field(None, title="Rc")
    rssi: float = Field(..., title="Rssi")
    sda: Optional[int] = Field(None, title="Sda")
    seen: float = Field(..., title="Seen")
    seen_pos: Optional[float] = Field(None, title="Seen Pos")
    sil: Optional[int] = Field(None, title="Sil")
    sil_type: Optional[str] = Field(None, title="Sil Type")
    spi: Optional[int] = Field(None, title="Spi")
    squawk: Optional[str] = Field(None, title="Squawk")
    t: Optional[str] = Field(None, title="T")
    tisb: list[str] = Field(..., title="Tisb")
    track: Optional[float] = Field(None, title="Track")
    type: str = Field(..., title="Type")
    version: Optional[int] = Field(None, title="Version")
    geom_rate: Optional[int] = Field(None, title="Geom Rate")
    db_flags: Optional[int] = Field(None, alias="dbFlags", title="Dbflags")
    nav_modes: Optional[list[str]] = Field(None, title="Nav Modes")
    true_heading: Optional[float] = Field(None, title="True Heading")
    ias: Optional[int] = Field(None, title="Ias")
    mach: Optional[float] = Field(None, title="Mach")
    mag_heading: Optional[float] = Field(None, title="Mag Heading")
    oat: Optional[int] = Field(None, title="Oat")
    roll: Optional[float] = Field(None, title="Roll")
    tas: Optional[int] = Field(None, title="Tas")
    tat: Optional[int] = Field(None, title="Tat")
    track_rate: Optional[float] = Field(None, title="Track Rate")
    wd: Optional[int] = Field(None, title="Wd")
    ws: Optional[int] = Field(None, title="Ws")
    gps_ok_before: Optional[float] = Field(None, alias="gpsOkBefore", title="Gpsokbefore")
    gps_ok_lat: Optional[float] = Field(None, alias="gpsOkLat", title="Gpsoklat")
    gps_ok_lon: Optional[float] = Field(None, alias="gpsOkLon", title="Gpsoklon")
    last_position: Optional[V2ResponseLastPosition] = Field(None, alias="lastPosition")
    rr_lat: Optional[float] = Field(None, title="Rr Lat")
    rr_lon: Optional[float] = Field(None, title="Rr Lon")
    calc_track: Optional[int] = Field(None, title="Calc Track")
    nav_altitude_fms: Optional[int] = Field(None, title="Nav Altitude Fms")


class V2ResponseModel(BaseModel):
    ac: list[V2ResponseAcItem] = Field(..., title="Ac")
    ctime: int = Field(..., title="Ctime")
    msg: str = Field(..., title="Msg")
    now: int = Field(..., title="Now")
    ptime: int = Field(..., title="Ptime")
    total: int = Field(..., title="Total")
